### ISSUE TITLE
Scoped dependencies don't show up in available updates

### ISSUE THREAD

**Issue by abierbaum** [bahmutov/next-update#87]
I am testing out next-updated with angular2 which has pakcages like:

    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.4",

When funning with --available, it does not seem to see that there is a new update for all of these dependencies.  (ex: 2.0.0-rc.5)

running `npm outdated` does see that the packages are out of date and could be updated.

Is this a known issue with scoped packages?

**Comment by bahmutov** [comment]
Probably not supported at all, will check.
